services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/qdrant/storage
  app:
    build:
      context: .
      dockerfile: src/app/Dockerfile
    ports:
      - 8501:8501
    environment:
      - QDRANT_URL=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
volumes:
  qdrant_data:    
